# Generated by Django 3.0.3 on 2020-12-09 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0002_auto_20201207_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Post Category'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Post'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='cat_id',
            field=models.ManyToManyField(to='frontend.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pst_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Post Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pst_title',
            field=models.CharField(max_length=150, verbose_name='Post Title'),
        ),
    ]
