# Generated by Django 3.1.1 on 2020-12-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='appear_home',
            field=models.CharField(choices=[('Feature', 'Appear on home'), ('No Feature', "Don't show on home"), ('Choose', 'Please Choose')], default='Choose', max_length=50),
        ),
    ]
