# Generated by Django 3.1.1 on 2020-12-18 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesearch',
            name='category',
        ),
        migrations.DeleteModel(
            name='ImageCategory',
        ),
        migrations.DeleteModel(
            name='ImageSearch',
        ),
    ]
